# Generated by Django 4.0.6 on 2022-08-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Картинка')),
                ('text', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ответ')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Блог',
                'db_table': 'blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Токен авторизации (нужен на этапе разработки)')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фамилия')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пол')),
                ('birth', models.IntegerField(blank=True, null=True, verbose_name='Дата рождения (timestamp)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Аватарка')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Статус блокировки')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Почта')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Отзыв')),
                ('mark', models.IntegerField(blank=True, default=2, null=True, verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва (timestamp)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.users', verbose_name='От кого')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='На кого')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
