# Generated by Django 3.2.6 on 2022-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_blocked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
