# Generated by Django 3.2.6 on 2022-07-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
