# Generated by Django 3.2.6 on 2022-08-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User'},
        ),
    ]
