# Generated by Django 4.0.6 on 2022-08-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, default='[1]', max_length=500, null=True, verbose_name='Место')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Создатель')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips', verbose_name='Поездка')),
            ],
            options={
                'verbose_name_plural': 'Список броней',
                'db_table': 'booking',
                'managed': True,
            },
        ),
    ]
