# Generated by Django 4.0.6 on 2022-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(blank=True, default='[0]', max_length=500, null=True, verbose_name='Место'),
        ),
    ]
