# Generated by Django 3.2.6 on 2022-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
    ]
