# Generated by Django 3.2.6 on 2022-08-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedusers',
            options={'managed': True, 'verbose_name': 'Banned user'},
        ),
    ]
