# Generated by Django 3.2.6 on 2022-08-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_conditioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='conditioner',
        ),
        migrations.AlterField(
            model_name='auto',
            name='count_of_passengers',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
