# Generated by Django 3.2.6 on 2022-08-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_conditioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='conditioner',
        ),
    ]
