# Generated by Django 3.2.6 on 2022-08-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220807_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'managed': True, 'verbose_name': 'Car'},
        ),
    ]
