# Generated by Django 4.0.6 on 2022-08-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('package', models.BooleanField(blank=True, default=False)),
                ('baggage', models.BooleanField(blank=True, default=False)),
                ('baby_chair', models.BooleanField(blank=True, default=False)),
                ('smoke', models.BooleanField(blank=True, default=False)),
                ('animals', models.BooleanField(blank=True, default=False)),
                ('two_places_in_behind', models.BooleanField(blank=True, default=False)),
                ('conditioner', models.BooleanField(blank=True, default=False)),
                ('premium', models.BooleanField(blank=True, default=False)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.auto')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'Trip',
                'db_table': 'trips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_to_previous', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
            options={
                'verbose_name': 'Stop',
                'db_table': 'stops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
            options={
                'db_table': 'departures',
                'managed': True,
            },
        ),
    ]
