# Generated by Django 3.2.6 on 2022-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20220703_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='baby_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='baggage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
