# Generated by Django 3.2.6 on 2022-08-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20220703_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='end',
        ),
        migrations.AddField(
            model_name='trips',
            name='animals',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='baby_chair',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='baggage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='package',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='smoke',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='two_places_in_behind',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_to_previous', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
            options={
                'db_table': 'stops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, default=None, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
            options={
                'db_table': 'departures',
                'managed': True,
            },
        ),
    ]
