# Generated by Django 3.2.6 on 2022-08-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20220805_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='conditioner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='premium',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
