# Generated by Django 3.2.6 on 2022-07-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220704_2250'),
        ('trips', '0003_auto_20220715_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='destination',
        ),
        migrations.AddField(
            model_name='trips',
            name='two_places_in_behind',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='animals',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='baby_chair',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='baggage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='package',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='smoke',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'destination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'departures',
                'managed': True,
            },
        ),
    ]
