# Generated by Django 3.2.6 on 2022-08-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20220807_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': True, 'verbose_name': 'Stop'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': True, 'verbose_name': 'Trip'},
        ),
        migrations.DeleteModel(
            name='TripsBooking',
        ),
    ]
