# Generated by Django 3.2.6 on 2022-07-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20220716_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips'),
        ),
    ]
