# Generated by Django 3.2.6 on 2022-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20220716_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='conditioner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
