# Generated by Django 3.2.6 on 2022-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trips_conditioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='premium',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
